- name: Create Nginx directories
  file:
    path: /opt/wordpress
    state: directory
    mode: '0755'

- name: Generate private key for SSL
  community.crypto.openssl_privatekey:
    path: /etc/ssl/wordpress/privkey.pem
    size: 2048
    mode: '0600'

- name: Generate a certificate signing request (CSR)
  community.crypto.openssl_csr:
    path: /etc/ssl/wordpress/req.csr
    privatekey_path: /etc/ssl/wordpress/privkey.pem
    common_name: "localhost"

- name: Generate self-signed SSL certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/wordpress/fullchain.pem
    csr_path: /etc/ssl/wordpress/req.csr
    privatekey_path: /etc/ssl/wordpress/privkey.pem
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    mode: '0644'
