- name: Ensure required Ansible collections are installed
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install community.docker collection
      ansible.builtin.shell: ansible-galaxy collection install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"
      changed_when: false

- name: Setup WordPress Platform
  hosts: all         # <----- Remove the dash!
  become: true
  roles:
    - common
    - docker
    - postgres
    - nginx
    - wordpress
    - monitoring
