- name: Check if Docker Compose directory exists
  stat:
    path: "{{ docker_compose_path }}"
  register: docker_compose_dir

- name: Remove existing Docker Compose directory
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: docker_compose_dir.stat.exists

- name: Create Docker Compose directory
  file:
    path: "{{ docker_compose_path }}"
    state: directory
    mode: '0755'

- name: Copy Nginx config for container mount
  template:
    src: nginx.conf.j2
    dest: "{{ docker_compose_path }}/nginx.conf"
    mode: '0644'
  when: docker_compose_path is defined

- name: Wait for PostgreSQL to become available
  wait_for:
    host: 127.0.0.1
    port: 5432
    delay: 5
    timeout: 60

- name: Copy Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    mode: '0644'

- name: Write .env file
  template:
    src: .env.j2
    dest: "{{ env_file_path }}"
    mode: '0644'

- name: Start or update Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}"
    state: present
    recreate: always
