- name: Create monitoring directory
  file:
    path: "{{ monitoring_path }}"
    state: directory
    mode: '0755'

- name: Copy prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_path }}/prometheus.yml"
    mode: '0644'

- name: Copy Docker Compose file for monitoring
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_path }}/docker-compose.yml"
    mode: '0644'

- name: Start Prometheus & Grafana via Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_path }}"
    state: present
    recreate: always
