- name: Create monitoring directory
  file:
    path: "{{ monitoring_path }}"
    state: directory
    mode: '0755'

- name: Create Grafana provisioning directories
  file:
    path: "{{ monitoring_path }}/grafana/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - provisioning/datasources
    - provisioning/dashboards
    - dashboards

- name: Copy prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_path }}/prometheus.yml"
    mode: '0644'

- name: Copy Grafana datasource config
  template:
    src: grafana-datasources.yml.j2
    dest: "{{ monitoring_path }}/grafana/provisioning/datasources/datasources.yml"
    mode: '0644'

- name: Copy Grafana dashboard config
  template:
    src: grafana-dashboards.yml.j2
    dest: "{{ monitoring_path }}/grafana/provisioning/dashboards/dashboards.yml"
    mode: '0644'

- name: Download Node Exporter dashboard
  get_url:
    url: "https://grafana.com/api/dashboards/1860/revisions/37/download"
    dest: "{{ monitoring_path }}/grafana/dashboards/node-exporter.json"
    mode: '0644'

- name: Download PostgreSQL dashboard
  get_url:
    url: "https://grafana.com/api/dashboards/9628/revisions/7/download"
    dest: "{{ monitoring_path }}/grafana/dashboards/postgres.json"
    mode: '0644'

- name: Download Nginx dashboard
  get_url:
    url: "https://grafana.com/api/dashboards/12708/revisions/1/download"
    dest: "{{ monitoring_path }}/grafana/dashboards/nginx.json"
    mode: '0644'

- name: Download Docker dashboard
  get_url:
    url: "https://grafana.com/api/dashboards/179/revisions/7/download"
    dest: "{{ monitoring_path }}/grafana/dashboards/docker.json"
    mode: '0644'

- name: Copy Docker Compose file for monitoring
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_path }}/docker-compose.yml"
    mode: '0644'

- name: Start Prometheus & Grafana via Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_path }}"
    state: present
    recreate: always