- name: Install required packages
  apt:
    name:
      - ufw
    state: present
    update_cache: yes

- name: Allow necessary ports in UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"     # HTTP
    - "443"    # HTTPS
    - "22"     # SSH
    - "3000"   # Grafana
    - "9090"   # Prometheus
    - "9100"   # Node Exporter
    - "9113"   # Nginx Exporter
    - "9187"   # PostgreSQL Exporter
  notify: Reload UFW

- name: Ensure UFW is enabled
  ufw:
    state: enabled